global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rag-agent'
    static_configs:
      - targets: ['rag-agent-app-prod:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['rag-agent-postgres-prod:9187']
    scrape_interval: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['rag-agent-redis-prod:9121']
    scrape_interval: 10s